import org.junit.Assert;
//import org.junit.Before;
import org.junit.Test;
/**
 * Compute the value generated by aspecified expression.
 * project 9
 * @author Xi Rao
 * @11/09/2018 
 */ 


public class BlueDiamondCardholderTest {
   

/** setTest. **/
   @Test public void setTest() {
      BlueDiamondCardholder bdc = new BlueDiamondCardholder(
         "10003", "King, Kelly");
      bdc.setBonusPurchasePoints(3000);
      Assert.assertEquals("getDiscountRate Test", 
         3000, bdc.getBonusPurchasePoints(), 0.001);
   }
/** getTest. **/
   @Test public void getTest() {
      BlueDiamondCardholder bdc = new BlueDiamondCardholder(
         "10003", "King, Kelly");
      Assert.assertEquals("getDiscountRate Test", 
         2500, bdc.getBonusPurchasePoints(), 0.001);
   }
   /** purchasePointsTest1. **/
   @Test public void purchasePointsTest1() {
      BlueDiamondCardholder bdc = new BlueDiamondCardholder(
         "10003", "King, Kelly"); 
      bdc.addPurchases(34.5, 100.0, 63.50, 300.0, 100.0); 
      bdc.setPrevBalance(1200.0);
      bdc.setBonusPurchasePoints(2500);
      Assert.assertEquals("purchasePoints Test1",
          2690, bdc.purchasePoints(), 0.001);
   }
/** purchasePointsTest2. **/
   @Test public void purchasePointsTest2() {
      BlueDiamondCardholder bdc2 = new BlueDiamondCardholder(
         "10004", "Jenkins, Jordan"); 
      bdc2.addPurchases(5000.0, 1000.0, 4000.0);
      bdc2.setPrevBalance(1200.0);
      Assert.assertEquals("purchasePoints Test2",
          47500, bdc2.purchasePoints(), 0.001);
   }
  /** toStringTest. **/
   @Test public void toStringTest() {
      BlueDiamondCardholder bdc = new BlueDiamondCardholder(
         "10003", "King, Kelly"); 
      bdc.addPurchases(34.5, 100.0, 63.50, 300.0, 100.0); 
      bdc.setPrevBalance(1200.0);
      bdc.setBonusPurchasePoints(2500);
      Assert.assertEquals("toString Test", 
         true, bdc.toString().contains(" "));
   }
   /** toStringTest1. **/
   @Test public void toStringTest1() {
      BlueDiamondCardholder bdc2 = new BlueDiamondCardholder(
         "10004", "Jenkins, Jordan"); 
      bdc2.addPurchases(5000.0, 1000.0, 4000.0);
      bdc2.setPrevBalance(1200.0);
      Assert.assertEquals("toString Test", 
         true, bdc2.toString().contains(" "));
   }
}