/**
 * Compute the value generated by aspecified expression.
 * project 10 
 * @author Xi Rao
 * @11/14/2018 
 */
public class SapphireCardholder extends Cardholder {
/**
    * @param acctNumberIn the acctNumber.
    * @param nameIn the name.
    */
   public SapphireCardholder(String acctNumberIn, String nameIn) {
      super(acctNumberIn, nameIn);
   }
/**
* @return purchasePoints.
*/
   public int purchasePoints() {
   
      int purchasePoints = (int) super.totalPurchases();
      return purchasePoints;
   }
}