import java.text.DecimalFormat; 
/**
 * Compute the value generated by aspecified expression.
 * project 10
 * @author Xi Rao
 * @11/14/2018 
 */
public class DiamondCardholder extends Cardholder {
   protected double discountRate = 0.05;
/**
    * @param acctNumberIn the acct number.
    * @param nameIn the name.
    * 
    */
   public DiamondCardholder(String acctNumberIn, String nameIn) {
      super(acctNumberIn, nameIn);
      category = "Diamond Cardholder";
   }
/**
* @param discountRateIn for the discount rate.
*/
   public void setDiscountRate(double discountRateIn) {
      discountRate = discountRateIn;
   }   
/**
* @return discount rate.
*/
   public double getDiscountRate() {
      return discountRate;
   }
/**
* @return purchase points.
*/
   
   public int purchasePoints() {
      int purchasePoints = (int) totalPurchases() * 3;
      return purchasePoints;
   }
   
 /**
* @return total purchases.
*/  
   public double totalPurchases() {
      return super.totalPurchases() * (1 - discountRate);
   } 
 /**
 * @return toString.
 */   
   
   public String toString() {
      DecimalFormat r = new DecimalFormat("0.0%");
      return super.toString()
         + "\n(includes " + r.format(discountRate) 
         + " discount rate applied to New Purchases)";
   }

}